config/routes.rb
Formbuilder::Application.routes.draw do

  #root to: 'home#show'
  root to:'forms#index'

  #resources :forms
  get 'forms/:id/fields' => 'forms#fields', :as => 'edit_form_fields'
  put 'forms/:id/fields' => 'forms#save_fields', :as => 'update_form_fields'

  #get 'forms/:form_id/responses/:id/thanks' => 'responses#thanks', :as => 'responses_thanks'
  get 'forms/:form_id/responses/thanks' => 'responses#thanks', :as => 'responses_thanks'

  resources :forms do
    #responses don't really need to be edited so no put/patch
       resources :responses

   end
end

app/models/field_response.rb
class FieldResponse < ActiveRecord::Base

  belongs_to :response

end

app/models/form.rb
class Form < ActiveRecord::Base



  validates :name, :presence => true

  has_many :form_fields, :dependent => :destroy

  has_many :responses, :dependent => :destroy

  after_create :postProcess

  def render_json

    self.to_json({:include => [:form_fields]}).html_safe

  end


  def render_responses_json
    self.responses.as_json(:include => [:field_responses])
  end

  def to_param
    urlref
  end

  def self.findByCode(r)
    where({:urlref => r}).first
  end



  private

  def postProcess
    self.urlref = SecureRandom.hex(8)

    self.save
  end


end

app/models/form_field.rb
class FormField < ActiveRecord::Base

  before_save :normalize_data

  serialize :field_options

  belongs_to :form

  default_scope order(:ordinality => :asc)

  private

  def normalize_data


    unless self.field_options.blank? || self.field_options[:options].blank?
      options = []

      self.field_options[:options].each do |i, option|
        options.push(option)
      end

      self.field_options[:options] = options

    end

  end

end

app/models/response.rb
class Response < ActiveRecord::Base


  belongs_to  :form
  has_many :field_responses


  def render_json
    self.to_json({:include => [:field_responses]}).html_safe
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  # GET /forms
  def index
    @forms = Form.all
  end

  # GET /forms/1
  def show

    #@form = Form.find(params[:id])
    @form = Form.findByCode(params[:id])

    respond_to do |format|

      if params[:callback]
        format.json { render :json => @form.render_json, :callback => params[:callback] }
      else
        format.json { render :json => @form.render_json }
      end
    format.html { }

    end
  end

  # GET /forms/new
  def new
    @form = Form.new
  end


=begin
  # GET /forms/1/edit
  def edit

    #@form = Form.find(params[:id])
    @form = Form.findByCode(params[:id])

  end
=end

  # POST /forms
  def create
    @form = Form.new(form_params)

    if @form.save
      #redirect_to edit_form_fields_path(@form), notice: 'Form was successfully created.'
      render action: 'edit' #does this ever get called?
    else
      render action: 'new'
    end
  end

  def update
    @form = Form.findByCode(params[:id])
    #@form = Form.find(params[:id])

    if @form.update_attributes(form_params)
      redirect_to forms_path, notice: 'Form was successfully updated.'
    else
      render action: 'edit'
    end

  end

  #def fields
  def edit
    #@form = Form.find(params[:id])
    @form = Form.findByCode(params[:id])
    @paste_code = paste_code(request.original_url)

  end

  def save_fields

    #@form = Form.find(params[:id])
    @form = Form.findByCode(params[:id])

    form_fields = params[:fields] ||= []
    valid_cid_list = []

    count = 0
    unless form_fields.empty?
      form_fields.each do |i, field|

        valid_cid_list.push(field[:cid])
        field[:ordinality] = count

        ff = @form.form_fields.find_by(:cid => field[:cid])

        if ff.nil?
          ff = @form.form_fields.build
        end

        ff.update_attributes(field)

        count = count+1

      end
    end

    # ignore currently set fields
    if valid_cid_list.length > 0
      @form.form_fields.where("form_fields.cid NOT IN (?)", valid_cid_list).delete_all
    else
      @form.form_fields.delete_all
    end

    respond_to do |format|
      format.json { render :json => @form.render_json }
    end

  end


  # DELETE /forms/1
  def destroy
    @form = Form.findByCode(params[:id])
    #@form = Form.find(params[:id])

    @form.destroy
    redirect_to forms_url, notice: 'Form config was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def form_params
    params.require(:form).permit(:name, :description, :active, :deleted, :response_id)
  end


#ugh...this kind of breaks my heart that this is here and not in the model...
  def paste_code(url)
    return '<html>
      <head>
      <link rel="stylesheet" type="text/css" href="informer.css">
      <link rel="stylesheet" type="text/css" href="../formbuilder/formbuilder.css">
    <script type="text/javascript">
        function staticLoadScript(url)
        {
            document.write(\'<script src="\', url, \'" type="text/JavaScript"><\/script>\');
        }
        if (typeof jQuery == \'undefined\'){ //Load the jQuery Lib, only if it is not already loaded by the browser in this scope.                                                                                                                                                                                                                        staticLoadScript("http://code.jquery.com/jquery-latest.min.js");
    }
    </script>
    <script type="text/javascript" src="informer.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#formHolder").emmbedFormBuilderFormFromUrl("'+"#{url}"+'.json?callback=?");
    });
    </script>
</head>
    <body>
    <div id="formHolder">
    </div>
    </body>
    </html>'
    #.gsub("<", "&lt;").gsub(">", "&gt;")

  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show

  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  before_action :load_form

  before_action :set_responses, only: [:show, :edit, :update, :destroy]


  def index
    @responses = @form.responses

    respond_to do |format|


      if params[:callback]
        format.json{render :json => @form.render_responses_json, :callback => params[:callback] }
      else
        format.json{render json: @form.render_responses_json}
      end
      format.html{}
    end

  end

  def show
       #@response = @form.responses.find(params[:id])

        #render :json => @responses.render_json

  end

  def new
    @responses = @form.responses.new
  end


  #def edit
    #@response = @form.responses.find(params[:id]) #this should be taken care of by set_response...
  #end

  def create
    @response = @form.responses.new




    respond_to do |format|
      if @response.save  # maybe redirect to a thanks url, with the referer page passed in a param? old school

        params.each do |key, val|
          if( key =~ /^c[0-9]+/ )
            puts "#{key} : #{val}"
            @response.field_responses.new(:key => key, :value => val).save

          end


        end



        #format.html { render :json => params }
        format.html { redirect_to action:"thanks"}
        format.json {} #probably not going to happen any time soon, unless we release a framework for
      else
        format.html { redirect_to action:"forms#index"}
        format.json {render json: @response.errors, status: :unprocessable_entity}
      end

    end

  end


  def thanks
    render layout:false
  end


  def update
    # for responses, there might not really be a need for an update....
  end

  def destroy
    #or to destroy....except perhaps by form creators...
  end

  private

  def set_responses
    @responses = @form.responses.find(params[:id]);
  end

  #don't trust params fromt he scary internets
  def response_params
    params.require(:response).permit(:form_id, :id, )
  end

  def load_form
    @form = Form.where("urlref = ? ", params[:form_id]).first
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/response_helper.rb
module ResponseHelper
end

app/views/forms/_form.html.erb
<%= simple_form_for @form, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :active %>
  <%= f.input :deleted %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                forms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1><%= @form.name %></h1>

<%= render :partial => 'form' %>

<link rel="stylesheet" href="/formbuilder/bower_components/font-awesome/css/font-awesome.css" />
<link rel="stylesheet" href="/formbuilder/formbuilder.css" />
<style>

    .fb-container {
        background-color: #444;
        font-family: sans-serif;
        padding:50px;
    }

    .fb-main {
        background-color: #fff;
        border-radius: 5px;
        min-height: 600px;
    }


    pre {
        background: #eee;
        padding: 10px;
        border: 2px solid #c94a29;
        overflow: hidden;
        margin: 0 0 15px 0;

        font-family: Courier, Monospace;
    }


    .sticky-top {
        position: fixed;
        top: 0;
    }
    .sticky-bottom{
        position:absolute;
        bottom:0;
    }

</style>


<div class="fb-container">

    <div class="fb-main"></div>

</div>

<script src="/formbuilder/bower_components/jquery/jquery.js"></script>
<script src="/formbuilder/bower_components/jquery-ui/ui/jquery.ui.core.js"></script>
<script src="/formbuilder/bower_components/jquery-ui/ui/jquery.ui.widget.js"></script>
<script src="/formbuilder/bower_components/jquery-ui/ui/jquery.ui.mouse.js"></script>
<script src="/formbuilder/bower_components/jquery-ui/ui/jquery.ui.draggable.js"></script>
<script src="/formbuilder/bower_components/jquery-ui/ui/jquery.ui.droppable.js"></script>
<script src="/formbuilder/bower_components/jquery-ui/ui/jquery.ui.sortable.js"></script>
<script src="/formbuilder/bower_components/jquery.scrollWindowTo/index.js"></script>
<script src="/formbuilder/bower_components/underscore/underscore-min.js"></script>
<script src="/formbuilder/bower_components/underscore.mixin.deepExtend/index.js"></script>
<script src="/formbuilder/bower_components/rivets/dist/rivets.js"></script>
<script src="/formbuilder/bower_components/backbone/backbone.js"></script>
<script src="/formbuilder/bower_components/backbone-deep-model/src/deep-model.js"></script>

<script src="/formbuilder/formbuilder.js"></script>

<script>
    $(function(){


        var currentForm = <%= @form.render_json %>;
        var form_fields = currentForm.form_fields;


        fb = new Formbuilder('.fb-main',
        {
            bootstrapData: form_fields
        });

        //fixing the left menu here...
        $window = $(window);
        $fbMain = $('.fb-main');
        $fbFloatMenu = $('.fb-left');
        fbFloatMenuTop = $fbFloatMenu.offset().top;
        fbMainBottom = $fbMain.offset().top + $fbMain.outerHeight(true);


        $window.unbind('scroll');//clear out the broken function from formbiulder.js

        //bind it to our working function...
        $window.on('scroll', function(){

//console.log(($window.scrollTop()+$fbFloatMenu.outerHeight(true))+' '+fbMainBottom); //yea this seems to have the right numbers.



            $fbFloatMenu.toggleClass('sticky-top', ($window.scrollTop() > fbFloatMenuTop) && (($window.scrollTop()+$fbFloatMenu.outerHeight(true)) < fbMainBottom));

            $fbFloatMenu.toggleClass('sticky-bottom',( ($window.scrollTop()+$fbFloatMenu.outerHeight(true)) >= fbMainBottom));



        });



        fb.on('save', function(payload)
        {
            //console.log(payload);
            $.ajax({
                url: '<%= update_form_fields_path(@form) %>',
                method: 'PUT',
                data: JSON.parse(payload)
                //complete: function(response)
                //{
                //    $("#response").html(response.responseText);
                //}
            })
        })






    });
</script>



<!--
<div class="well">
  <span>Copy and paste this code into your html to embed your form on an external site.</span>
  <pre id="codebox">
    <code>
      <%= @paste_code %>
    </code>


  </pre>

</div>

  -->

app/views/forms/index.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:deleted) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= link_to form.id, form_path(form) %></td>
        <td><%= form.name %></td>
        <td><%= form.description %></td>
        <td><%= form.active %></td>
        <td><%= form.deleted %></td>
        <td><%=l form.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_form_path(form), :class => 'btn btn-mini' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      form_path(form),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>

          <%= link_to t('Responses'), form_responses_path(form), :class => 'btn btn-mini' %>


        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_form_path,
            :class => 'btn btn-primary' %>

app/views/forms/new.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/forms/old_edit.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/forms/show.html.erb
<%- model_class = Form -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @form.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @form.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @form.active %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deleted) %>:</strong></dt>
  <dd><%= @form.deleted %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")), forms_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_form_path(@form), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              form_path(@form),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Formbuilder" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Formbuilder</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", root_path  %></li>
              <li><%= link_to "Forms", forms_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container content">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>

        </div><!--/row-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/responses/_form.html.erb
<%= simple_form_for(@responses) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Responses to '<%= @form.name %>'</h1>

<table>
  <thead>
    <tr>
      <th>Response ID</th>
      <th>Created at</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>

        <td><%= link_to response.id, form_response_path(response.form ,response) %></td>
        <td><%= response.created_at.to_formatted_s(:short) %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

<%= link_to 'Back', form_responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_form_response_path %> |
<%= link_to 'Back', form_responses_path %>

app/views/responses/thanks.html.erb
<html>
<body>
<h2>Thanks</h2>

<p>this isn't the real thank you page, or even a default thank you page.  We just wanted to say thanks.</p>

</body>
</html>